name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version}}
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt


      - name: Lint with flake8
        run: flake8 .

      - name: Run tests
        run: pytest -q --junitxml=report.xml

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.xml


  smoke:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependendcies
        run: pip install -r requirements.txt

      - name: Start application
        run: |
          python app.py &
          sleep 5 

      - name: Run health check 
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health)
          test "$code"="200" 